CREATE DATABASE PROGRAMA_TV;
USE PROGRAMA_TV;

CREATE TABLE PROGRAMA (
IDPROGRAMA INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(40),
GENERO VARCHAR(30),
EMISSORA VARCHAR(20)
);

INSERT INTO PROGRAMA  VALUES
(null,'Jesus domingo de manhã','Religioso','Record'),
(null,'The Good Doctor','Drama','Globo'),
(null,'Dr House','Drama','Record'),
(null,'Bob esponja','Comédia','SBT'),
(null,'Naruto','Drama','SBT'),
(null,'Padrinhos mágicos','Comédia','SBT'),
(null,'Liga da Justiça','Ação','SBT');
 
 SELECT * FROM PROGRAMA;
 SELECT  NOME, EMISSORA FROM PROGRAMA;
SELECT * FROM PROGRAMA WHERE EMISSORA= 'SBT';
SELECT * FROM PROGRAMA WHERE GENERO= 'Drama';
SELECT * FROM PROGRAMA ORDER BY GENERO;
SELECT * FROM PROGRAMA ORDER BY NOME DESC;
SELECT * FROM PROGRAMA WHERE NOME LIKE'%a';
SELECT * FROM PROGRAMA WHERE GENERO LIKE'D%';
SELECT * FROM PROGRAMA WHERE EMISSORA LIKE'_B%';
SELECT * FROM PROGRAMA WHERE EMISSORA LIKE'%B_';

UPDATE PROGRAMA SET EMISSORA = 'SBT' WHERE IDPROGRAMA = 1;
DELETE  FROM PROGRAMA WHERE IDPROGRAMA=7;
-- DROP TABLE PROGRAMA;
 
