/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.simulador.alerta;

import java.awt.AWTException;
import java.awt.Image;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.Timer;

/**
 *
 * @author pedro
 */
public class Tela extends javax.swing.JPanel {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        Random aleatorio = new Random();//(max - min) + 1) + min
        ActionListener actionCPU, actionRAM, actionHD, actionGPU;
        actionCPU = (ActionEvent actionEvent) -> {
            lblCPU.setText(String.format("%d%%", aleatorio.nextInt((90 - 60) + 1) + 60));
        };
        actionRAM = (ActionEvent actionEvent) -> {
            lblRAM.setText(String.format("%d%%", aleatorio.nextInt((90 - 50) + 1) + 50));
        };
        actionHD = (ActionEvent actionEvent) -> {
            lblHD.setText(String.format("%d%%", aleatorio.nextInt((90 - 70) + 1) + 70));
        };
        actionGPU = (ActionEvent actionEvent) -> {
            lblGPU.setText(String.format("%d%%", aleatorio.nextInt((1 - 0) + 1) + 0));
        };

        Timer timerCPU = new Timer(1000, actionCPU);
        Timer timerRAM = new Timer(2000, actionRAM);
        Timer timerHD = new Timer(10000, actionHD);
        Timer timerGPU = new Timer(1500, actionGPU);

        timerCPU.start();
        timerRAM.start();
        timerHD.start();
        timerGPU.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCPU = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblRAM = new javax.swing.JLabel();
        lblHD = new javax.swing.JLabel();
        lblGPU = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCPU = new javax.swing.JButton();
        btnRAM = new javax.swing.JButton();
        btnHD = new javax.swing.JButton();
        btnGPU = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("CPU.....................................");

        lblCPU.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCPU.setText("60%");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("RAM.....................................");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("HD........................................");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("GPU......................................");

        lblRAM.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblRAM.setText("50%");

        lblHD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblHD.setText("70%");

        lblGPU.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblGPU.setText("0%");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simulador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        btnCPU.setText("CPU");
        btnCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPUActionPerformed(evt);
            }
        });

        btnRAM.setText("RAM");
        btnRAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRAMActionPerformed(evt);
            }
        });

        btnHD.setText("HD");
        btnHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHDActionPerformed(evt);
            }
        });

        btnGPU.setText("GPU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCPU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRAM)
                .addGap(18, 18, 18)
                .addComponent(btnHD)
                .addGap(18, 18, 18)
                .addComponent(btnGPU)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCPU)
                    .addComponent(btnRAM)
                    .addComponent(btnHD)
                    .addComponent(btnGPU))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCPU, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                    .addComponent(lblRAM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblGPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCPU))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRAM)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblHD))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblGPU))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPUActionPerformed
        lblCPU.setText("100%");
        Image image = Toolkit.getDefaultToolkit().getImage("");
        TrayIcon trayIcon = new TrayIcon(image);

        if (SystemTray.isSupported()) {
            SystemTray tray = SystemTray.getSystemTray();

            try {
                tray.add(trayIcon);
                trayIcon.displayMessage("Simulando", "Sua CPU está em 100%", TrayIcon.MessageType.WARNING);
            } catch (AWTException e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_btnCPUActionPerformed

    private void btnRAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRAMActionPerformed
        lblRAM.setText("100%");
        Image image = Toolkit.getDefaultToolkit().getImage("");
        TrayIcon trayIcon = new TrayIcon(image);

        if (SystemTray.isSupported()) {
            SystemTray tray = SystemTray.getSystemTray();

            try {
                tray.add(trayIcon);
                trayIcon.displayMessage("Simulando", "Você está usando 100% da sua RAM", TrayIcon.MessageType.NONE);
            } catch (AWTException e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_btnRAMActionPerformed

    private void btnHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHDActionPerformed
        lblHD.setText("100%");
        Image image = Toolkit.getDefaultToolkit().getImage("");
        TrayIcon trayIcon = new TrayIcon(image);

        if (SystemTray.isSupported()) {
            SystemTray tray = SystemTray.getSystemTray();

            try {
                tray.add(trayIcon);
                trayIcon.displayMessage("Simulando", "HD está com 100% da sua capacidade.", TrayIcon.MessageType.ERROR);
            } catch (AWTException e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_btnHDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCPU;
    private javax.swing.JButton btnGPU;
    private javax.swing.JButton btnHD;
    private javax.swing.JButton btnRAM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCPU;
    private javax.swing.JLabel lblGPU;
    private javax.swing.JLabel lblHD;
    private javax.swing.JLabel lblRAM;
    // End of variables declaration//GEN-END:variables
}
